/**
 * This file automatically has been generated by ULS and
 *  contains an implementation of lexical analyzer
 *  for parsing the programming language 'css3'.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
#pragma once

#include <uls/UlsLex.h>
#include <string>

namespace uls {
	namespace collection {
		class Css3LexBasis : public uls::crux::UlsLex {
		  public:
			static const int          CSS_ERR = -8;
			static const int         CSS_NONE = -7;
			static const int         CSS_LINK = -6;
			static const int         CSS_TMPL = -5;
			static const int      CSS_LINENUM = -4;
			static const int          CSS_NUM = -3;
			static const int           CSS_ID = -2;
			static const int          CSS_EOF = -1;

			static const int          CSS_EOI = 0;

			static const int          CSS_URL = 4;
			static const int           CSS_PX = 5;
			static const int           CSS_EM = 6;
			static const int           CSS_EX = 7;
			static const int          CSS_DEG = 8;
			static const int           CSS_PT = 9;

			static const int           CSS_PC = 10;
			static const int           CSS_MM = 11;
			static const int           CSS_CM = 12;
			static const int         CSS_INCH = 13;
			static const int         CSS_PATH = 14;
			static const int     CSS_SELECTOR = 15;
			static const int       CSS_DQUOTE = 34;
			static const int       CSS_SQUOTE = 39;

			Css3LexBasis(std::tstring& ulc_fpath)
				 : uls::crux::UlsLex(ulc_fpath) {}
		};
	}
}
