/**
 * This file automatically has been generated by ULS and
 *  contains an implementation of lexical analyzer
 *  for parsing the programming language 'ulc'.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 * 
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef __ULC_LEX_H__
#define __ULC_LEX_H__

#define             NONE  -7
#define             LINK  -6
#define             TMPL  -5
#define          LINENUM  -4
#define          TOK_TAB  9

#define           TOK_LF  10
#define       TOK_BLKSEP  258
#define         TOK_TRUE  259

#define        TOK_FALSE  260

#define ATTR_WANT_LF_TOK  261
#define ATTR_WANT_TAB_TOK  262
#define ATTR_WANT_EOF_TOK  263
#define ATTR_CASE_SENSITIVE  264
#define ATTR_COMMENT_TYPE  265
#define  ATTR_QUOTE_TYPE  266
#define ATTR_ID_FIRST_CHARS  267
#define    ATTR_ID_CHARS  268
#define      ATTR_RENAME  269

#define ATTR_FILE_VERSION  270
#define          TOK_ERR  273
#define          TOK_EOI  274
#define          TOK_EOF  275
#define          TOK_NUM  276
#define           TOK_ID  277
#define         TOK_WORD  278

#endif

