#ifndef __ULS_CONST_LINUX_H__
#define __ULS_CONST_LINUX_H__

#define ONECHAR_TOKGRP_TYPE00_ULS_N_ONECHAR_TOKGRPS onechar_tokgrp_s00array4
#define TWOPLUS_TREE_TYPE00_ULS_KWTABLE_TWOPLUS_SIZE twoplus_tree_s00array14
#define NUMBER_PREFIX_TYPE00_ULS_N_MAX_NUMBER_PREFIXES number_prefix_s00array8
#define STDIO_BOX_TYPE00_ULS_N_BOXLST stdio_box_s00array3
#define CMD_TYPE00_ULC_N_LEXATTRS cmd_s00array13
#define SYSPROP_TYPE00_ULS_N_SYSPROPS sysprop_s00array16

#endif
