/**
 * This file automatically has been generated by ULS and
 *  contains an implementation of lexical analyzer
 *  for parsing the programming language 'eng'.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
#pragma once

#include <uls/UlsLex.h>
#include <string>

namespace uls {
	namespace collection {
		class EngLexBasis : public uls::crux::UlsLex {
		  public:
			static const int              ERR = -8;
			static const int             NONE = -7;
			static const int             LINK = -6;
			static const int             TMPL = -5;
			static const int          LINENUM = -4;
			static const int              NUM = -3;
			static const int             WORD = -2;
			static const int          ENDFILE = -1;

			static const int              EOI = 0;

			static const int             THAT = 1;
			static const int               WE = 2;
			static const int               OR = 3;
			static const int             ELSE = 4;
			static const int              AND = 5;
			static const int               BE = 6;
			static const int              THE = 7;
			static const int               IS = 8;
			static const int            WHICH = 9;

			static const int              EOL = 10;
			static const int               NO = 11;
			static const int            THERE = 12;
			static const int                A = 13;
			static const int               AN = 14;
			static const int            WHERE = 15;
			static const int           BEFORE = 16;
			static const int             FROM = 17;
			static const int              HIS = 18;
			static const int               TO = 19;

			static const int               IN = 20;
			static const int              I_M = 21;
			static const int           YOU_RE = 22;
			static const int             I_LL = 23;
			static const int           DQUOTE = 34;

			EngLexBasis(std::tstring& ulc_fpath)
				 : uls::crux::UlsLex(ulc_fpath) {}
		};
	}
}
