/**
 * This file automatically has been generated by ULS and
 *  contains an implementation of lexical analyzer
 *  for parsing the programming language 'shell'.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
#pragma once

#include <uls/UlsLex.h>
#include <string>

namespace uls {
	namespace collection {
		class ShellLexBasis : public uls::crux::UlsLex {
		  public:
			static const int              ERR = -8;
			static const int             NONE = -7;
			static const int             LINK = -6;
			static const int             TMPL = -5;
			static const int          LINENUM = -4;
			static const int              NUM = -3;
			static const int             WORD = -2;
			static const int          ENDFILE = -1;

			static const int              EOI = 0;

			static const int              AND = 4;
			static const int               OR = 5;
			static const int               EQ = 6;

			static const int              EOL = 10;
			static const int               NE = 11;
			static const int              EOP = 12;
			static const int            BREAK = 13;
			static const int             BYTE = 14;
			static const int             CASE = 15;
			static const int             ESAC = 16;
			static const int          DEFAULT = 17;
			static const int               DO = 18;
			static const int             DONE = 19;

			static const int             ELSE = 20;
			static const int             ELIF = 21;
			static const int              FOR = 22;
			static const int               IF = 23;
			static const int             THEN = 24;
			static const int               FI = 25;
			static const int           RETURN = 26;
			static const int         CONTINUE = 27;
			static const int            WHILE = 28;
			static const int            LOCAL = 29;

			static const int              VAR = 30;
			static const int           SELECT = 31;
			static const int         FUNCTION = 32;
			static const int           DQUOTE = 34;
			static const int           SQUOTE = 39;
			static const int             ININ = 48;
			static const int         REDIRECT = 49;

			static const int         NOQUOTE2 = 50;
			static const int        NUM_PARMS = 50;
			static const int         NOQUOTE1 = 92;
			static const int           IQUOTE = 96;

			ShellLexBasis(std::tstring& ulc_fpath)
				 : uls::crux::UlsLex(ulc_fpath) {}
		};
	}
}
