/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uls_polaris_UlsOStream */

#ifndef _Included_uls_polaris_UlsOStream
#define _Included_uls_polaris_UlsOStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uls_polaris_UlsOStream
 * Method:    createOFile
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_uls_polaris_UlsOStream_createOFile
  (JNIEnv *, jclass, jstring, jobject, jstring);

/*
 * Class:     uls_polaris_UlsOStream
 * Method:    destroyOFile
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uls_polaris_UlsOStream_destroyOFile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     uls_polaris_UlsOStream
 * Method:    printTok
 * Signature: (Ljava/lang/Object;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_uls_polaris_UlsOStream_printTok
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     uls_polaris_UlsOStream
 * Method:    printTokLinenum
 * Signature: (Ljava/lang/Object;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_uls_polaris_UlsOStream_printTokLinenum
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     uls_polaris_UlsOStream
 * Method:    startStream
 * Signature: (Ljava/lang/Object;I)Z
 */
JNIEXPORT jboolean JNICALL Java_uls_polaris_UlsOStream_startStream
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     uls_polaris_UlsOStream
 * Method:    getFlagLineNumbering
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uls_polaris_UlsOStream_getFlagLineNumbering
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
