/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uls_polaris_UlsStream */

#ifndef _Included_uls_polaris_UlsStream
#define _Included_uls_polaris_UlsStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uls_polaris_UlsStream
 * Method:    destroyIFile
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uls_polaris_UlsStream_destroyIFile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     uls_polaris_UlsStream
 * Method:    destroyOFile
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uls_polaris_UlsStream_destroyOFile
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
