/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uls_polaris_UlsIStream */

#ifndef _Included_uls_polaris_UlsIStream
#define _Included_uls_polaris_UlsIStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uls_polaris_UlsIStream
 * Method:    openIFile
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_uls_polaris_UlsIStream_openIFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uls_polaris_UlsIStream
 * Method:    destroyIFile
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uls_polaris_UlsIStream_destroyIFile
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
